name: Publish to crates.io

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --locked

      - name: Test cargo install
        run: |
          cargo install --locked --debug --path .
